#!/usr/bin/env python3

import json
import types
from http.server import HTTPServer, BaseHTTPRequestHandler
import sys

import core

def shell():
	import code
	code.InteractiveConsole(locals=locals()).interact()

class Handler(BaseHTTPRequestHandler):
	def do_GET(self):
		if self.path == '/': return
		id = self.path[1:]
		self.send_response(302)
		name = core.id_or_name_to_name(id)
		url = core.name_to_leetcode_url(name)
		self.send_header('Location', url)
		self.end_headers()

def main():
	args = sys.argv[1:]
	if len(args) > 0: port = int(args[0])
	else: port = 8080
	print(f'Listening on port {port}.')
	HTTPServer(("", port), Handler).serve_forever()

if __name__ == '__main__': main()
